[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
airbag_protocol = "HwH7yKX4copxVziXv1U9SxdR4m3FkE7PTEH4sa1Zpfcn"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
